WITH SUSTAINABILITY_PREFERENCE AS (
  SELECT DISTINCT SUSTAINABILITY_PREFERENCE AS SUSTAINABILITY_PREFERENCE
  FROM ONTOLOGY_DATA OD WHERE OD.CONDITIONAL=TRUE
), 
LINES AS (
  SELECT 'DROP VIEW IF EXISTS V_PRIMARY_SUSTAINABILITY_INFORMATION; ' AS PART
  UNION ALL 
  SELECT 'CREATE VIEW V_PRIMARY_SUSTAINABILITY_INFORMATION AS '
  UNION ALL
  SELECT ' SELECT SOURCE, PRODUCT_IDX ' 
  UNION ALL
  SELECT ', AVG(ASSOCIATION_IMP_SCORE) FILTER (WHERE SUSTAINABILITY_PREFERENCE = "' || SUSTAINABILITY_PREFERENCE || '") AS "' || TRIM(REPLACE(	UPPER(SUSTAINABILITY_PREFERENCE), 'PRODUCTS', '')) || '" '
  FROM SUSTAINABILITY_PREFERENCE
  UNION ALL
  SELECT 'FROM (SELECT POM.SOURCE, POM.PRODUCT_IDX, OD.SUSTAINABILITY_PREFERENCE, 
POM.IMP_SCORE*OD.ASSOCIATION AS ASSOCIATION_IMP_SCORE 
FROM PRODUCT_ONTOLOGY_MAPPING POM 
LEFT JOIN ONTOLOGY_DATA OD 
ON POM.ONTO_IDX=OD.IDX WHERE OD.CONDITIONAL=TRUE) GROUP BY SOURCE, PRODUCT_IDX ORDER BY SOURCE, PRODUCT_IDX;'
)
SELECT GROUP_CONCAT(PART, '')
FROM LINES;