DROP TABLE IF EXISTS ONTOLOGY_DATA;
CREATE TABLE ONTOLOGY_DATA(
IDX INTEGER PRIMARY KEY,
TAG TEXT,
SUSTAINABILITY_PREFERENCE TEXT,
PREFERENCE_CATEGORY TEXT,
ASSOCIATION DECIMAL(10,5),
CONDITIONAL BOOLEAN CHECK (CONDITIONAL IN (0, 1))
);
DROP TABLE IF EXISTS VOCABULARY;
CREATE TABLE VOCABULARY(
IDX INTEGER PRIMARY KEY,
VOCAB TEXT
);
DROP TABLE IF EXISTS PRODUCT_DATA;
CREATE TABLE PRODUCT_DATA(
SOURCE TEXT,
IDX INTEGER,
PRODUCT_CODE TEXT,
PRODUCT_TITLE TEXT,
PRODUCT_DESCRIPTION CLOB,
PRODUCT_CATEGORY TEXT,
PRICE DECIMAL(10,5),
BRAND TEXT,
PRIMARY KEY (SOURCE, IDX)
);
DROP TABLE IF EXISTS PRODUCT_KEYWORDS;
CREATE TABLE PRODUCT_KEYWORDS(
SOURCE TEXT NOT NULL,
PRODUCT_IDX INTEGER NOT NULL,
VOCAB_IDX INTEGER,
PRIMARY KEY (SOURCE, PRODUCT_IDX, VOCAB_IDX),
FOREIGN KEY(SOURCE, PRODUCT_IDX) 
	REFERENCES PRODUCT_DATA(SOURCE, PRODUCT_IDX)
         ON DELETE CASCADE 
         ON UPDATE NO ACTION,
FOREIGN KEY(VOCAB_IDX) 
	REFERENCES VOCABULARY(VOCAB_IDX)
         ON DELETE CASCADE 
         ON UPDATE NO ACTION
);
DROP TABLE IF EXISTS PRODUCT_ONTOLOGY_MAPPING;
CREATE TABLE PRODUCT_ONTOLOGY_MAPPING(
SOURCE TEXT NOT NULL,
PRODUCT_IDX INTEGER NOT NULL,
ONTO_IDX INTEGER NOT NULL,
IMP_SCORE DECIMAL(10,5),
PRIMARY KEY (SOURCE, PRODUCT_IDX, ONTO_IDX),
FOREIGN KEY(SOURCE, PRODUCT_IDX) 
	REFERENCES PRODUCT_DATA(SOURCE, PRODUCT_IDX)
         ON DELETE CASCADE 
         ON UPDATE NO ACTION,
FOREIGN KEY(ONTO_IDX) 
	REFERENCES ONTOLOGY_DATA(ONTO_IDX)
         ON DELETE CASCADE 
         ON UPDATE NO ACTION
);