DROP VIEW IF EXISTS V_KEYWORDS_FREQ; 
CREATE VIEW V_KEYWORDS_FREQ AS
SELECT V.VOCAB, COUNT(*) AS FREQ FROM PRODUCT_KEYWORDS PK
JOIN VOCABULARY V ON V.IDX=PK.VOCAB_IDX
GROUP BY V.IDX, V.VOCAB
ORDER BY FREQ DESC; 

DROP VIEW IF EXISTS V_SUSTAINABILITY_PRODUCT_INFO; 
CREATE VIEW V_SUSTAINABILITY_PRODUCT_INFO AS
SELECT PD."SOURCE", PD."IDX" AS "PRODUCT_IDX", PD.PRODUCT_TITLE, PD.PRODUCT_DESCRIPTION, K.KEYWORDS,
ROUND("HEALTH", 4) AS "HEALTH", 
ROUND("SOCIAL",4) AS "SOCIAL", ROUND("ENVIRONMENT",4) AS "ENVIRONMENT", 
ROUND("QUALITY", 4) AS "QUALITY", ROUND("VEGAN",4) AS "VEGAN", 
ROUND("GLUTEN-FREE",4) AS "GLUTEN-FREE", ROUND("VEGETARIAN",4) AS "VEGETARIAN", 
ROUND("LACTOSE-FREE",4) AS "LACTOSE-FREE", ROUND("ALLERGEN-FREE",4) AS "ALLERGEN-FREE"
FROM
(SELECT  PK.SOURCE, PK.PRODUCT_IDX, GROUP_CONCAT(VOCAB, ', ') AS KEYWORDS 
FROM PRODUCT_KEYWORDS PK
LEFT JOIN VOCABULARY V ON PK.VOCAB_IDX=V.IDX
GROUP BY PK.SOURCE, PK.PRODUCT_IDX) K
LEFT JOIN PRODUCT_DATA PD ON PD.IDX=K.PRODUCT_IDX AND PD.SOURCE=K.SOURCE
LEFT JOIN V_PRIMARY_SUSTAINABILITY_INFORMATION PSI ON PD.SOURCE=PSI.SOURCE AND PD.IDX=PSI.PRODUCT_IDX
LEFT JOIN V_SUPPLEMENTARY_SUSTAINABILITY_INFORMATION SSI ON PD.SOURCE=SSI.SOURCE AND PD.IDX=SSI.PRODUCT_IDX
;