WITH PREFERENCE_CATEGORY AS (
  SELECT DISTINCT PREFERENCE_CATEGORY AS PREFERENCE_CATEGORY
  FROM ONTOLOGY_DATA
), 
LINES AS (
  SELECT 'DROP VIEW IF EXISTS V_SUPPLEMENTARY_SUSTAINABILITY_INFORMATION; ' AS PART
  UNION ALL 
  SELECT 'CREATE VIEW V_SUPPLEMENTARY_SUSTAINABILITY_INFORMATION AS '
  UNION ALL
  SELECT ' SELECT SOURCE, PRODUCT_IDX ' 
  UNION ALL
  SELECT ', AVG(ASSOCIATION_IMP_SCORE) FILTER (WHERE PREFERENCE_CATEGORY = "' || PREFERENCE_CATEGORY || '") AS "' || LOWER(PREFERENCE_CATEGORY) || '" '
  FROM PREFERENCE_CATEGORY
  UNION ALL
  SELECT 'FROM (SELECT POM.SOURCE, POM.PRODUCT_IDX, OD.PREFERENCE_CATEGORY, 
POM.IMP_SCORE*OD.ASSOCIATION AS ASSOCIATION_IMP_SCORE 
FROM PRODUCT_ONTOLOGY_MAPPING POM 
LEFT JOIN ONTOLOGY_DATA OD 
ON POM.ONTO_IDX=OD.IDX WHERE OD.CONDITIONAL=FALSE) GROUP BY SOURCE, PRODUCT_IDX ORDER BY SOURCE, PRODUCT_IDX;'
)
SELECT GROUP_CONCAT(PART, '')
FROM LINES;

